const tarifa: number      = 0.50;
const numeroRuta: number  = 42;
const velocidadPromedio: number = 45.5;
const hexColorBus: number    = 0x00A86B;  
const emailChofer: string    = "conductor@transporte.com";
const tipoVehiculo: string = 'Autobús Articulado';
const rutaApi: string     = `/api/v1/rutas`;
const busEnServicio: boolean  = true;
const requiereMantenimiento: boolean = false;
const esNocturno: boolean      = false;
const pasajesVendidos = 1500;
const pasajesDescuento = 300;
const pasajesNormales = pasajesVendidos - pasajesDescuento;  
const conductor = "  juan.perez@transporte.com  ";
console.log(conductor.trim().toLowerCase()); 
console.log(emailChofer.includes("transporte"));    
console.log(emailChofer.split("@"));              
console.log(emailChofer.split("@")[1]); 
let registro: string ="Bus42;Sur;15;08-10-2023";
console.log(registro.split(";")[0]);         
const puedeCircular: boolean = busEnServicio && !requiereMantenimiento;
console.log(puedeCircular); 
