const tiemposLlegada: number[] = [5, 12, 18, 25, 30];
const estaciones: Array<string> = ["Norte", "Centro", "Sur"];   
const pasajerosPorParada = [10, 20, 30]; 
console.log(`Tiempos de llegada: ${tiemposLlegada}`);
console.log(`Estaciones: ${estaciones}`);
console.log(`Pasajeros: ${pasajerosPorParada}`);
const retrasos: number[] = tiemposLlegada.map((t) => t + 5);       
const cercanos: number[] = tiemposLlegada.filter((t) => t <= 15); 
const totalPasajeros: number = pasajerosPorParada.reduce((acc, p) => acc + p, 0); 
console.log(`Retrasos: ${retrasos}`);
console.log(`Cercanos: ${cercanos}`);
console.log(`Total Pasajeros: ${totalPasajeros}`);
tiemposLlegada.push(40);       
tiemposLlegada.unshift(1);    
const ultimoTiempo = tiemposLlegada.pop();   
const primerTiempo = tiemposLlegada.shift(); 
console.log(`Después de mutaciones: ${tiemposLlegada}`);
console.log(`Primero: ${primerTiempo}, Último: ${ultimoTiempo}`);
const hayRutaAlCentro: boolean = estaciones.includes("Centro"); 
console.log(`Existe estación Centro: ${hayRutaAlCentro}`);
const indiceSur: number = estaciones.indexOf("Sur");      
console.log(`Índice de estación Sur: ${indiceSur}`);
const esperaLarga: number | undefined = tiemposLlegada.find((t) => t > 20); 
console.log(`Espera larga encontrada: ${esperaLarga}`); 
